"""LLM-written narrative report + its deterministic fallback (Phase 176).

Division of labour, stated once so it stays true
------------------------------------------------
The engine decides.  The model only writes prose about what the engine
decided.  Concretely:

  * the model receives target info + a compact digest of real findings
    (type, severity, url, param, method, context, payload, transform, the
    engine's own detail line, and the corpus remediation advice)
  * the model is told, in the prompt, that it may not invent or alter a
    single fact -- and :func:`_verify_facts` re-checks afterwards that every
    URL and payload the model echoed really exists in the digest.  Anything
    it made up is flagged in the report footer rather than shown as truth
  * no finding is added, removed, re-typed or re-graded by the model.  The
    authoritative findings live in the machine-readable report; this module
    only produces a narrative *section*

Degradation is mandatory, not optional
--------------------------------------
An LLM pool can be entirely rate-limited / blocked / offline.  When that
happens :func:`build_ai_report` does NOT raise -- it produces the same
report structure from ``fix_advice``'s curated corpus (the deterministic
path that predates this module) and labels it as such.  A scan always ends
with a usable report.

Security note: LLM output is escaped before any HTML tag is generated
(see :func:`_md_to_html`).  The report is a document people open in a
browser, and the text it contains is, by construction, full of live attack
strings -- a model that echoes a payload must not be able to turn the report
itself into a vector.  Escape first, then decorate.
"""
from __future__ import annotations

import html as _html
import json
import re
import time
from dataclasses import dataclass, field
from typing import Any

from .logger import get_logger

_log = get_logger("report_ai")

#: Digest caps -- keep the prompt bounded no matter how big the scan was.
MAX_FINDINGS_DEFAULT = 25
_PAYLOAD_CAP = 200
_DETAIL_CAP = 300
_URL_CAP = 300

#: A structurally complete report (summary + rating + details + priority) runs
#: 1500+ characters in practice.  Below this floor the completion is not a
#: report, it is an artefact -- live case: sensenova/glm-5.2 spent its whole
#: 1500-token budget on reasoning and returned 95 characters with a 200.
#: Passing this floor to the pool turns that into a failover.
MIN_REPORT_CHARS = 200

_SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
_SEV_LABEL = {"critical": "严重", "high": "高危", "medium": "中危",
              "low": "低危", "info": "信息"}

# ---------------------------------------------------------------------------
# Bilingual copy (the fallback template must read well without any model)
# ---------------------------------------------------------------------------

_COPY = {
    "zh": {
        "title": "AI 分析",
        "degraded_note": "本报告由确定性模板生成（AI 撰写不可用：{reason}）。"
                         "内容取自内置修复建议语料库，未经模型改写。",
        "ai_note": "本节由大模型（{model}）根据扫描器输出的客观结果撰写。"
                   "所有漏洞类型、严重度、URL、参数与载荷均来自确定性检测引擎，"
                   "模型不得新增或修改事实。",
        "summary": "执行摘要",
        "rating": "风险评级",
        "details": "漏洞详情",
        "priority": "修复优先级建议",
        "target": "目标",
        "generated": "生成时间",
        "requests": "请求数",
        "waf": "WAF",
        "sev": "严重度",
        "count": "数量",
        "type": "类型",
        "url": "URL",
        "param": "参数",
        "method": "方法",
        "context": "上下文",
        "payload": "载荷",
        "cause": "成因",
        "impact": "影响",
        "verify": "复现",
        "fix": "修复",
        "cwe": "CWE",
        "also": "另需考虑",
        "none": "本次扫描未发现 XSS 相关缺陷。",
        "truncated": "（另有 {n} 条未在此列出，完整清单见机器可读报告。）",
        "no_findings": "未发现漏洞",
        "meta_line": "目标 {target} · 共 {n} 条发现 · 生成于 {generated}",
        "critical_first": "存在严重/高危缺陷，建议立即修复。",
        "medium_first": "存在中危缺陷，建议在下一个迭代内修复。",
        "low_only": "仅存在低危/信息级缺陷，可按常规节奏处理。",
        "unverified": "以下条目中的 {n} 处内容未能与扫描结果核对一致，"
                      "已标注，请以机器可读报告为准：{items}",
        "provider_line": "撰写模型：{provider}/{model}（切换 {failovers} 次）",
        "fallback_line": "撰写方式：确定性模板（未调用模型）",
    },
    "en": {
        "title": "AI Analysis",
        "degraded_note": "This section was generated by the deterministic "
                         "template (AI writing unavailable: {reason}). It uses "
                         "the built-in remediation corpus verbatim.",
        "ai_note": "Written by {model} from the scanner's objective output. "
                   "Every type, severity, URL, parameter and payload comes from "
                   "the deterministic engine; the model may not add or alter "
                   "facts.",
        "summary": "Executive Summary",
        "rating": "Risk Rating",
        "details": "Finding Details",
        "priority": "Remediation Priority",
        "target": "Target",
        "generated": "Generated",
        "requests": "Requests",
        "waf": "WAF",
        "sev": "Severity",
        "count": "Count",
        "type": "Type",
        "url": "URL",
        "param": "Param",
        "method": "Method",
        "context": "Context",
        "payload": "Payload",
        "cause": "Cause",
        "impact": "Impact",
        "verify": "Reproduce",
        "fix": "Fix",
        "cwe": "CWE",
        "also": "Also consider",
        "none": "No XSS-related defect was found in this scan.",
        "truncated": "({n} more finding(s) omitted here; see the "
                     "machine-readable report for the full list.)",
        "no_findings": "no findings",
        "meta_line": "Target {target} · {n} finding(s) · generated {generated}",
        "critical_first": "Critical/high defects are present -- remediate now.",
        "medium_first": "Medium-severity defects are present -- fix in the next "
                        "iteration.",
        "low_only": "Only low/info defects -- handle on the normal cadence.",
        "unverified": "{n} statement(s) could not be matched against the scan "
                      "results and are flagged; trust the machine-readable "
                      "report: {items}",
        "provider_line": "Written by: {provider}/{model} "
                         "({failovers} failover(s))",
        "fallback_line": "Written by: deterministic template (no model called)",
    },
}


# ---------------------------------------------------------------------------
# Result holder
# ---------------------------------------------------------------------------

@dataclass
class AIReport:
    """The narrative section, in both renderings, plus how it was produced."""

    markdown: str = ""
    html: str = ""
    ok: bool = False                # True only when a model wrote it
    used_llm: bool = False
    provider: str = ""
    model: str = ""
    failovers: int = 0
    elapsed: float = 0.0
    error: str = ""                 # why we degraded (empty when ok)
    attempts: list[dict] = field(default_factory=list)
    fact_warnings: list[str] = field(default_factory=list)
    finding_count: int = 0

    @property
    def degraded(self) -> bool:
        return not self.used_llm

    def to_meta(self) -> dict:
        """JSON-safe view, for ``meta['ai_report']`` and the JSON report."""
        return {
            "ok": self.ok,
            "used_llm": self.used_llm,
            "degraded": self.degraded,
            "provider": self.provider,
            "model": self.model,
            "failovers": self.failovers,
            "elapsed": round(self.elapsed, 2),
            "error": self.error,
            "fact_warnings": list(self.fact_warnings),
            "finding_count": self.finding_count,
            "attempts": list(self.attempts),
            "markdown": self.markdown,
            "html": self.html,
        }


# ---------------------------------------------------------------------------
# Digest: findings -> a bounded prompt payload
# ---------------------------------------------------------------------------

def _d(f) -> dict:
    return f.data if hasattr(f, "data") else f


def _clip(s: Any, n: int) -> str:
    t = "" if s is None else str(s)
    t = t.replace("\r", " ").replace("\n", " ")
    return t if len(t) <= n else t[: n - 1] + "…"


def summarize_findings(findings: list, max_findings: int = MAX_FINDINGS_DEFAULT
                       ) -> tuple[list[dict], dict]:
    """Turn findings into a compact, severity-ordered digest.

    Returns ``(rows, stats)``.  Rows are capped so the prompt stays bounded on
    a scan that produced hundreds of findings; ``stats`` reports both the
    total and the omitted count so the model (and the reader) knows the
    digest is partial rather than pretending it is complete.
    """
    from . import fix_advice

    by_sev: dict[str, int] = {}
    by_type: dict[str, int] = {}
    for f in findings:
        d = _d(f)
        sev = str(d.get("severity") or "info")
        ftype = str(d.get("type") or "unknown")
        by_sev[sev] = by_sev.get(sev, 0) + 1
        by_type[ftype] = by_type.get(ftype, 0) + 1

    ordered = sorted(
        findings,
        key=lambda f: (_SEV_ORDER.get(str(_d(f).get("severity") or "info"), 9),),
    )

    rows: list[dict] = []
    for i, f in enumerate(ordered[:max_findings], 1):
        d = _d(f)
        ftype = str(d.get("type") or "unknown")
        try:
            adv = fix_advice.get_advice(ftype)
        except Exception:
            adv = {}
        poc = d.get("poc") or {}
        rows.append({
            "n": i,
            "type": ftype,
            "severity": str(d.get("severity") or "info"),
            "url": _clip(d.get("url"), _URL_CAP),
            "method": str(d.get("method") or "GET"),
            "param": d.get("param") or "",
            "context": str(d.get("context") or ""),
            "payload": _clip(d.get("payload"), _PAYLOAD_CAP),
            "transform": list(d.get("transform") or []),
            "detail": _clip(d.get("detail") or d.get("evidence"), _DETAIL_CAP),
            "confidence": str(d.get("confidence") or ""),
            "cvss": d.get("cvss_score"),
            "cwe": d.get("cwe") or adv.get("primary_cwe", ""),
            "poc_curl": _clip(poc.get("curl"), _PAYLOAD_CAP),
            "engine_fix_headline": _clip(adv.get("headline"), _DETAIL_CAP),
            "engine_fix_detail": _clip(adv.get("detail"), _DETAIL_CAP),
        })

    stats = {
        "total": len(findings),
        "by_severity": by_sev,
        "by_type": by_type,
        "included": len(rows),
        "omitted": max(0, len(findings) - len(rows)),
    }
    return rows, stats


# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

_SYSTEM_ZH = """你是一名资深 Web 安全工程师，负责为自动化 XSS 扫描器的输出撰写正式报告。

硬性约束：
1. 只能使用输入中提供的事实（URL、参数、方法、上下文、载荷、严重度、类型、引擎给出的 detail 与修复建议）。禁止编造任何未提供的漏洞、参数、影响、复现步骤或统计数据。
2. 禁止修改输入的严重度、漏洞类型、URL、参数、载荷。如认为判定可疑，只在对应条目下以"备注"形式说明，不得改写事实。
3. 输出纯 Markdown，不要用代码围栏包裹整篇报告，不要寒暄、不要额外开场白。
4. 结构必须严格如下：

## 执行摘要
（2-4 句：目标、发现数量与严重度分布、整体风险判断）

## 风险评级
（一个 Markdown 表格：严重度 / 数量）

## 漏洞详情
（每条发现一个小节，标题格式 ### 序号. [严重度] 类型 — 精简 URL）
（小节内用列表给出：成因、影响、复现、修复、CWE）

## 修复优先级建议
（有序列表，按优先修复顺序给出可执行建议）

5. 语言：简体中文。风格专业、简洁，面向研发与安全负责人。
6. 如果发现列表为空，如实说明未发现缺陷，不要虚构。"""

_SYSTEM_EN = """You are a senior web security engineer writing the formal
report section for an automated XSS scanner's output.

Hard constraints:
1. Use ONLY the facts given in the input (URL, parameter, method, context,
   payload, severity, type, the engine's detail line and remediation advice).
   Never invent vulnerabilities, parameters, impact, reproduction steps or
   statistics that are not present.
2. Never alter the given severity, type, URL, parameter or payload. If a
   verdict looks questionable, add a "Note" under that item -- do not rewrite
   the facts.
3. Output plain Markdown. Do not wrap the whole report in a code fence, do
   not add pleasantries or a preamble.
4. Structure exactly:

## Executive Summary
## Risk Rating
## Finding Details
### <n>. [<severity>] <type> -- <short url>
(each item lists: Cause / Impact / Reproduce / Fix / CWE)
## Remediation Priority

5. Professional, concise, aimed at engineers and security owners.
6. If the finding list is empty, say so plainly and do not invent anything."""


def build_prompt(rows: list[dict], stats: dict, target: str, meta: dict,
                 lang: str = "zh") -> list[dict]:
    """Build the chat messages.  Facts in, prose out, nothing else."""
    lang = lang if lang in _COPY else "zh"
    system = _SYSTEM_ZH if lang == "zh" else _SYSTEM_EN
    payload = {
        "target": target,
        "generated": meta.get("generated", ""),
        "requests_made": meta.get("requests", 0),
        "waf": meta.get("waf") or "none detected",
        "scan_stats": stats,
        "findings": rows,
    }
    user = (
        "以下是一次自动化 XSS 扫描的客观结果（JSON）。请据此撰写报告。\n\n"
        "```json\n" + json.dumps(payload, ensure_ascii=False, indent=1) + "\n```\n"
    ) if lang == "zh" else (
        "Objective results of one automated XSS scan (JSON) follow. Write the "
        "report from them.\n\n```json\n"
        + json.dumps(payload, ensure_ascii=False, indent=1) + "\n```\n"
    )
    return [{"role": "system", "content": system},
            {"role": "user", "content": user}]


# ---------------------------------------------------------------------------
# Output cleaning
# ---------------------------------------------------------------------------

#: Tags some models emit around their reasoning channel.
_REASON_TAGS = ("</think", "</thinking", "</reasoning", "</analysis",
                "</scratchpad", "</internal")
#: Deliberately narrow: only unambiguous reasoning-channel tags.  Including
#: generic names like ``answer``/``output`` would silently eat a payload that
#: happens to contain a literal ``<output>`` tag.
_REASON_TAG_RE = re.compile(
    r"</?\s*(think|thinking|reasoning|analysis|scratchpad|internal)\b[^>]*>",
    re.I)
#: A whole-report code fence, opening and optional trailing fence.
_FENCE_RE = re.compile(r"^\s*```[a-zA-Z0-9_+-]*[ \t]*\r?\n(?P<body>.*?)(?:\r?\n```\s*)?$",
                       re.S)


def clean_completion(text: str) -> str:
    """Strip reasoning-channel leakage and stray fences from a completion.

    Observed live with ``amd/MiniCPM5-2B``: the whole chain of thought came
    back before the answer, separated by a closing ``</think`` tag::

        我们被要求根据提供的JSON数据撰写报告。报告必须遵循…… </think>

        ## 执行摘要
        …real report…

    Order matters here: the opening code fence must go FIRST.  Stripping the
    preamble before the fence would remove the opening ```` ``` ```` while
    leaving the trailing one behind, which then defeats the fence regex.

    Stage by stage:

    1. a whole-report code fence (the prompt forbids it; models still do it);
    2. reasoning channel -- if a close tag is present, keep only what follows;
    3. otherwise, if a ``##`` heading exists past the first line, drop
       everything before it (the prompt fixes the output shape, so a first
       line that is not a heading is by definition preamble).

    Nothing is ever *added*, so a well-behaved model -- whose output starts at
    ``## 执行摘要`` on line 1 -- passes through untouched.
    """
    if not text:
        return ""
    t = text.strip()

    # 1. Whole-report fence first (see docstring for why).
    m = _FENCE_RE.match(t)
    if m and m.group("body").strip():
        t = m.group("body").strip()
    # A stray trailing fence whose opener was already consumed.
    if t.endswith("```"):
        t = t[:-3].rstrip()

    # 2. Reasoning channel: drop everything up to and including the close tag.
    lower = t.lower()
    cut = -1
    for tag in _REASON_TAGS:
        i = lower.find(tag)
        if i != -1:
            gt = t.find(">", i)
            cand = gt + 1 if gt != -1 else i + len(tag)
            if cand > cut:
                cut = cand
    if cut > 0:
        t = t[cut:]
    t = _REASON_TAG_RE.sub("", t).strip()

    # 3. Preamble without a tag: a report always opens on a '##' heading.
    if not t.startswith("#"):
        h = re.search(r"^##\s", t, flags=re.M)
        if h and h.start() > 0:
            t = t[h.start():]

    return t.strip()


# ---------------------------------------------------------------------------
# Fact verification (the model writes prose, not facts)
# ---------------------------------------------------------------------------

def _verify_facts(text: str, rows: list[dict],
                  extra_urls: list[str] | None = None) -> list[str]:
    """Flag URLs / payloads the model quoted that are NOT in the digest.

    ``extra_urls`` carries legitimate non-finding URLs the model is expected to
    reference -- above all the scan TARGET, which is in the prompt's metadata
    and which any summary naturally names.  Without it every report about a
    clean scan gets a false "unverified content" warning: with zero findings
    there are no finding URLs at all, so the target was the only URL in the
    text and got reported as invented.  (Observed live on an API scan of a
    reflector that produced 0 findings.)

    A cheap, deliberately conservative check: it only looks at quoted URLs and
    backticked payload-looking strings, and reports what it cannot attribute.
    It never edits the text -- a false accusation is worse than a missed one
    here, so the bar is "this looks like a real URL/payload and it appears
    nowhere in the input".
    """
    if not text:
        return []
    known_urls = {r["url"] for r in rows if r.get("url")}
    known_urls |= {u for u in (extra_urls or []) if u}
    known_payloads = {r["payload"] for r in rows if r.get("payload")}
    # Hosts are enough: models legitimately shorten a long URL to its path.
    known_hosts = set()
    for u in known_urls:
        m = re.search(r"https?://([^/\s]+)", u)
        if m:
            known_hosts.add(m.group(1).lower())

    warnings: list[str] = []
    for m in re.finditer(r"https?://[^\s`)\]>,，。；\"]+", text):
        u = m.group(0).rstrip(".")
        mh = re.search(r"https?://([^/\s]+)", u)
        if not mh:
            continue
        if mh.group(1).lower() in known_hosts:
            continue
        if any(u in ku or ku.startswith(u) for ku in known_urls):
            continue
        if u not in warnings:
            warnings.append(u)
    for m in re.finditer(r"`([^`\n]{8,200})`", text):
        s = m.group(1).strip()
        if not any(t in s for t in ("<", "onerror", "onload", "alert(", "javascript:")):
            continue
        if s in known_payloads:
            continue
        if any(s in kp or kp in s for kp in known_payloads if kp):
            continue
        if s not in warnings:
            warnings.append(s)
    return warnings[:10]


# ---------------------------------------------------------------------------
# Minimal, escape-first Markdown -> HTML
# ---------------------------------------------------------------------------

def _inline(s: str) -> str:
    """Decorate an ALREADY-ESCAPED line with inline markup."""
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<!\*)\*(?!\s)(.+?)(?<!\s)\*(?!\*)", r"<em>\1</em>", s)
    # Double backticks first: models wrap commands in ``...`` (CommonMark's
    # way of quoting a span that may itself contain one backtick).  Live case:
    # ``curl -i 'http://...'`` rendered with literal backticks, mangling the
    # one part of the report a reader actually copy-pastes.
    s = re.sub(r"``([^`\n]+)``", r"<code>\1</code>", s)
    s = re.sub(r"`([^`\n]+)`", r"<code>\1</code>", s)
    return s


def _md_to_html(md: str) -> str:
    """Convert the model's Markdown to report HTML.

    Escape-first: every character is entity-escaped before any tag is
    synthesised, so a payload the model quotes can never execute in the
    reader's browser.  Supports headings, lists, tables, bold/italic/code and
    paragraphs -- the subset the prompt asks for.
    """
    if not md:
        return ""
    text = md.strip()
    # Strip a whole-report code fence if the model wrapped everything.
    text = re.sub(r"^\s*```[a-zA-Z]*\s*\n(.*)\n```\s*$", r"\1", text,
                  flags=re.S)
    out: list[str] = []
    list_open: str | None = None
    in_table = False
    para: list[str] = []

    def flush_para():
        if para:
            out.append("<p>" + _inline(" ".join(para)) + "</p>")
            para.clear()

    def close_list():
        nonlocal list_open
        if list_open:
            out.append(f"</{list_open}>")
            list_open = None

    def close_table():
        nonlocal in_table
        if in_table:
            out.append("</tbody></table>")
            in_table = False

    for raw in text.split("\n"):
        line = _html.escape(raw.rstrip(), quote=False)
        stripped = line.strip()

        if stripped.startswith("|") and stripped.endswith("|"):
            close_list()
            flush_para()
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= set("-: ") and c for c in cells):
                continue  # separator row
            if not in_table:
                out.append('<table class="ai-table"><tbody>')
                in_table = True
            out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in cells)
                       + "</tr>")
            continue
        close_table()

        if not stripped:
            flush_para()
            close_list()
            continue

        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            flush_para()
            close_list()
            # Shifted down one level and capped at h4: the section already
            # carries an <h2> from ai_section_html, so the model's '##' must
            # become h3 and its '###' h4 -- otherwise a top-level section
            # heading and a per-finding heading would collide at the same
            # depth and the report would read flat.
            lvl = min(4, len(m.group(1)) + 1)
            out.append(f"<h{lvl}>{_inline(m.group(2))}</h{lvl}>")
            continue

        m = re.match(r"^[-*+]\s+(.*)$", stripped)
        if m:
            flush_para()
            if list_open != "ul":
                close_list()
                out.append("<ul>")
                list_open = "ul"
            out.append(f"<li>{_inline(m.group(1))}</li>")
            continue

        m = re.match(r"^\d+[.)]\s+(.*)$", stripped)
        if m:
            flush_para()
            if list_open != "ol":
                close_list()
                out.append("<ol>")
                list_open = "ol"
            out.append(f"<li>{_inline(m.group(1))}</li>")
            continue

        m = re.match(r"^&gt;\s*(.*)$", stripped)
        if m:
            flush_para()
            close_list()
            out.append(f'<blockquote>{_inline(m.group(1))}</blockquote>')
            continue

        para.append(stripped)

    flush_para()
    close_list()
    close_table()
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Deterministic fallback (the pre-existing, corpus-driven path)
# ---------------------------------------------------------------------------

def template_report(findings: list, target: str, meta: dict,
                    reason: str = "", lang: str = "zh") -> str:
    """Build the same structure without any model, from the advice corpus.

    This is the safety net: an unreachable pool must still yield a report a
    human can act on.  Content comes from ``data/fix_advice.json`` verbatim,
    so nothing here is invented -- which is exactly why it is an acceptable
    substitute when the model is not available.
    """
    from . import fix_advice

    c = _COPY.get(lang, _COPY["zh"])
    rows, stats = summarize_findings(findings, max_findings=10 ** 6)

    lines: list[str] = []
    if reason:
        lines.append(f"> {c['degraded_note'].format(reason=reason)}")
        lines.append("")

    # -- executive summary -------------------------------------------------
    lines.append(f"## {c['summary']}")
    lines.append("")
    if not findings:
        lines.append(c["none"])
    else:
        counts = stats["by_severity"]
        dist = " · ".join(f"{k}: {counts[k]}"
                          for k in sorted(counts, key=lambda s: _SEV_ORDER.get(s, 9)))
        worst = min(counts, key=lambda s: _SEV_ORDER.get(s, 9))
        if _SEV_ORDER.get(worst, 9) <= 1:
            verdict = c["critical_first"]
        elif _SEV_ORDER.get(worst, 9) <= 2:
            verdict = c["medium_first"]
        else:
            verdict = c["low_only"]
        lines.append(f"{c['meta_line'].format(target=target, n=stats['total'], generated=meta.get('generated', ''))}")
        lines.append("")
        lines.append(f"{dist}。{verdict}")
    lines.append("")

    # -- risk rating -------------------------------------------------------
    if findings:
        lines.append(f"## {c['rating']}")
        lines.append("")
        lines.append(f"| {c['sev']} | {c['count']} |")
        lines.append("|---|---|")
        counts = stats["by_severity"]
        for sev in sorted(counts, key=lambda s: _SEV_ORDER.get(s, 9)):
            lines.append(f"| {sev} | {counts[sev]} |")
        lines.append("")

    # -- details -----------------------------------------------------------
    if findings:
        lines.append(f"## {c['details']}")
        lines.append("")
        for r in rows:
            url_short = r["url"]
            if len(url_short) > 80:
                url_short = url_short[:77] + "…"
            lines.append(f"### {r['n']}. [{r['severity']}] {r['type']} — {url_short}")
            lines.append("")
            adv = fix_advice.get_advice(r["type"])
            if r.get("param"):
                lines.append(f"- **{c['param']}**：`{r['param']}`")
            lines.append(f"- **{c['method']}**：`{r['method']}`")
            if r.get("context"):
                lines.append(f"- **{c['context']}**：`{r['context']}`")
            if r.get("payload"):
                lines.append(f"- **{c['payload']}**：`{r['payload']}`")
            if r.get("detail"):
                lines.append(f"- {r['detail']}")
            if adv.get("detail"):
                lines.append(f"- **{c['impact']} / {c['cause']}**：{adv['detail']}")
            if r.get("poc_curl"):
                lines.append(f"- **{c['verify']}**：`{r['poc_curl']}`")
            if adv.get("headline"):
                lines.append(f"- **{c['fix']}**：{adv['headline']}")
            cwe = r.get("cwe") or adv.get("primary_cwe")
            if cwe:
                lines.append(f"- **{c['cwe']}**：{cwe}")
            also = adv.get("also_consider") or []
            if also:
                lines.append(f"- **{c['also']}**：" + "；".join(also))
            lines.append("")

    # -- priority ----------------------------------------------------------
    if findings:
        lines.append(f"## {c['priority']}")
        lines.append("")
        seen: list[str] = []
        for r in rows:
            if r["type"] not in seen:
                seen.append(r["type"])
        for i, t in enumerate(seen, 1):
            adv = fix_advice.get_advice(t)
            n = stats["by_type"].get(t, 0)
            lines.append(f"{i}. `{t}`（{n} 处）— {adv.get('headline', '')}")
        lines.append("")

    if stats.get("omitted"):
        lines.append(c["truncated"].format(n=stats["omitted"]))
        lines.append("")
    return "\n".join(lines).strip() + "\n"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def build_ai_report(findings: list, target: str, meta: dict | None = None, *,
                    pool=None, config_path: str | None = None,
                    models: list[str] | None = None,
                    lang: str = "zh",
                    max_findings: int = MAX_FINDINGS_DEFAULT,
                    timeout: float | None = None,
                    verify_facts: bool = True) -> AIReport:
    """Produce the narrative section, never raising on LLM failure.

    On success: a model written section + routing info.
    On any failure (no config, all candidates rate-limited/blocked, bad
    output): the deterministic template, with ``error`` explaining why.
    """
    meta = meta or {}
    lang = lang if lang in _COPY else "zh"
    rep = AIReport(finding_count=len(findings))
    t0 = time.time()

    rows, stats = summarize_findings(findings, max_findings)

    resolved_pool = pool
    if resolved_pool is None:
        try:
            from .llm_pool import LLMPool
            resolved_pool = LLMPool.from_file(config_path)
        except Exception as e:
            # No pool configured / unreadable: straight to template.
            reason = f"{type(e).__name__}: {e}"
            _log.warning("ai report: no usable LLM pool (%s); using template",
                         reason)
            rep.error = reason
            rep.markdown = template_report(findings, target, meta, reason, lang)
            rep.html = _md_to_html(rep.markdown)
            rep.elapsed = time.time() - t0
            return rep

    messages = build_prompt(rows, stats, target, meta, lang)
    try:
        result = resolved_pool.complete(messages, models=models,
                                        timeout=timeout,
                                        min_chars=MIN_REPORT_CHARS)
    except Exception as e:
        reason = _short_reason(e)
        _log.warning("ai report: pool exhausted (%s); using template", reason)
        rep.error = reason
        rep.attempts = [a.to_dict() for a in getattr(e, "attempts", [])]
        rep.markdown = template_report(findings, target, meta, reason, lang)
        rep.html = _md_to_html(rep.markdown)
        rep.elapsed = time.time() - t0
        return rep

    # Some models leak their reasoning channel ahead of the answer; strip it
    # before anything downstream sees the text (see clean_completion).
    text = clean_completion(result.text or "")
    if not text:
        # A 200 with nothing in it -- same treatment as a failure.
        reason = "model returned an empty completion"
        rep.error = reason
        rep.attempts = [a.to_dict() for a in result.attempts]
        rep.markdown = template_report(findings, target, meta, reason, lang)
        rep.html = _md_to_html(rep.markdown)
        rep.elapsed = time.time() - t0
        return rep

    c = _COPY[lang]
    header = [
        f"> {c['ai_note'].format(model=result.candidate.model)}",
        f"> {c['provider_line'].format(provider=result.candidate.provider_id, model=result.candidate.model, failovers=result.failovers)}",
        "",
    ]
    if verify_facts:
        # The target is legitimate context -- it is in the prompt's metadata,
        # so naming it is not invention.
        warnings = _verify_facts(text, rows, extra_urls=[target])
        if warnings:
            rep.fact_warnings = warnings
            items = "；".join(f"`{w}`" for w in warnings)
            header.append(f"> ⚠️ {c['unverified'].format(n=len(warnings), items=items)}")
            header.append("")

    md = "\n".join(header) + text.rstrip() + "\n"
    rep.markdown = md
    rep.html = _md_to_html(md)
    rep.ok = True
    rep.used_llm = True
    rep.provider = result.candidate.provider_id
    rep.model = result.candidate.model
    rep.failovers = result.failovers
    rep.attempts = [a.to_dict() for a in result.attempts]
    rep.elapsed = time.time() - t0
    return rep


def _short_reason(e: BaseException) -> str:
    """Human-readable one-liner for why the LLM path failed."""
    try:
        from .llm_pool import LLMPoolExhausted
        if isinstance(e, LLMPoolExhausted):
            kinds: dict[str, int] = {}
            for a in getattr(e, "attempts", []):
                kinds[a.kind] = kinds.get(a.kind, 0) + 1
            if kinds:
                detail = ", ".join(f"{k} x{v}" for k, v in kinds.items())
                return f"all candidates failed ({detail})"
    except Exception:
        pass
    return f"{type(e).__name__}: {str(e)[:160]}"


def ai_section_html(ai_meta: dict) -> str:
    """Render the AI section for the HTML report from ``meta['ai_report']``."""
    if not isinstance(ai_meta, dict):
        return ""
    body = ai_meta.get("html") or ""
    if not body:
        return ""
    cls = "ai-report degraded" if ai_meta.get("degraded") else "ai-report"
    return (f'<section class="{cls}">'
            f'<h2>{_html.escape(_COPY["zh"]["title"])}</h2>'
            f'{body}</section>')


def ai_section_markdown(ai_meta: dict) -> str:
    """Render the AI section for the Markdown report."""
    if not isinstance(ai_meta, dict):
        return ""
    md = ai_meta.get("markdown") or ""
    if not md:
        return ""
    return f"## {_COPY['zh']['title']}\n\n{md}\n"
