"""WAF / filter fingerprinting from response signals.

Detects common blocking signatures so the scanner can adapt (report the WAF,
and the transform engine can prioritize encoding families). This is heuristic
and conservative to avoid false positives.

Detection signals used (in priority order):
  1. Specific response headers (Server, X-Powered-By, Via, X-Cache, etc.)
  2. Vendor-specific cookies (__cfduid, incap_ses, SERVERID, etc.)
  3. Block-page body signatures (vendor error pages, default block messages)
  4. Status code patterns (403, 406, 419, 999, 502-from-WAF, etc.)

The detect() function returns a dict describing the WAF (if any), whether
the request was blocked, and the reason.  Vendors are matched in order of
specificity -- if multiple signals match, the most specific one wins.
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# WAF vendor signatures
#
# Each entry: (vendor_name, regex_on_headers_body, signal_kind)
# signal_kind is one of:
#   "cookie"  -- matched against Set-Cookie values
#   "header"  -- matched against response header names/values
#   "body"    -- matched against response body (first 8KB)
#   "any"     -- matched against headers + body
# Ordered by specificity: vendors with unique cookies first, then header
# matches, then body-only matches.
# ---------------------------------------------------------------------------
_WAF_SIGNATURES: list[tuple[str, "re.Pattern[str]", str]] = [
    # --- Cloudflare family ---
    ("Cloudflare",
     re.compile(r"cloudflare|__cfduid|cf-ray|cf-cache-status|__cf_bm|"
                r"cf-request-id|cf-mitigated", re.I), "any"),
    ("Cloudflare Enterprise",
     re.compile(r"cf-ray|server:\s*cloudflare", re.I), "header"),

    # --- Akamai ---
    ("Akamai",
     re.compile(r"akamaighost|akamai|akamaized|x-akamai-transformed|"
                r"akamai-grn|ak_bmsc|bm_sz|bm_mi|bm_sv", re.I), "any"),
    ("Akamai Kona Site Defender",
     re.compile(r"akamai\b[^.]*\.[\w.]+kona|kona_rule", re.I), "body"),

    # --- AWS WAF / Shield ---
    ("AWS WAF",
     re.compile(r"x-amzn-requestid|x-amzn-waf|awselb|x-amz-cf-id|"
                r"x-amz-cf-pop|awswaf|aws-waf", re.I), "any"),
    ("AWS CloudFront",
     re.compile(r"x-amz-cf-id|via:\s*1\.1\.\w+\.cloudfront\.net", re.I), "any"),
    ("AWS Shield Advanced",
     re.compile(r"x-amzn-err-type|aws-shield", re.I), "any"),

    # --- Imperva / Incapsula ---
    ("Imperva Incapsula",
     re.compile(r"incap_ses|x-iinfo|visid_incap|incap_ses_|"
                r"dotomi|imperva|incapsula", re.I), "any"),
    ("Imperva SecureSphere",
     re.compile(r"imperva.securesphere|SecureSphere", re.I), "body"),

    # --- F5 ---
    ("F5 BIG-IP ASM",
     re.compile(r"bigipserver|ts01|tsa|BIGipServer|f5ip|"
                r"webshields|TS0[0-9a-f]+", re.I), "any"),
    ("F5 ASM",
     re.compile(r"the requested url was rejected|F5 ASM", re.I), "body"),

    # --- Wordfence / WordPress WAFs ---
    ("Wordfence",
     re.compile(r"wordfence|wfvt_|wfwaf-", re.I), "any"),
    ("Sucuri CloudProxy",
     re.compile(r"sucuri|x-sucuri-id|sucuri_cloudproxy", re.I), "any"),
    ("BBQ Pure",
     re.compile(r"bbq_", re.I), "cookie"),
    ("iThemes Security",
     re.compile(r"ithemes-security", re.I), "any"),

    # --- ModSecurity / OWASP CRS ---
    ("ModSecurity",
     re.compile(r"mod_security|modsecurity|this error was generated by "
                r"mod_security|Mod_Security", re.I), "any"),
    ("OWASP CRS",
     re.compile(r"OWASP CRS|ModSecurity-.*OWASP|crs_rule", re.I), "body"),

    # --- Barracuda / FortiWeb / Citrix ---
    ("Barracuda",
     re.compile(r"barracuda|barra_counter_session", re.I), "any"),
    ("FortiWeb",
     re.compile(r"fortiweb|FortiWeb|fortinet", re.I), "any"),
    ("Citrix Netscaler",
     re.compile(r"citrix|netscaler|ns_af=", re.I), "any"),

    # --- Cisco / Juniper / Sophos ---
    ("Cisco ACE",
     re.compile(r"cisco|ace-|cisco_ace", re.I), "any"),
    ("Juniper WebApp Secure",
     re.compile(r"juniper|jroute|jsessionid_jws", re.I), "any"),
    ("Sophos UTM",
     re.compile(r"sophos|utm-", re.I), "any"),

    # --- DenyAll / Wallarm / Astra / ReSEC ---
    ("DenyAll",
     re.compile(r"sessioncookie|denyall|rweb_security", re.I), "any"),
    ("Wallarm",
     re.compile(r"wallarm|nginx-wallarm", re.I), "any"),
    ("Astra",
     re.compile(r"astra|x-astra", re.I), "any"),
    ("ReSEC",
     re.compile(r"resec|security_resec", re.I), "any"),

    # --- Edgecast / Fastly / Qrator / Distil ---
    ("Edgecast",
     re.compile(r"edgecast|ecd", re.I), "any"),
    ("Fastly",
     re.compile(r"fastly|x-served-by.*cache|cache-control.*fastly", re.I), "any"),
    ("Qrator",
     re.compile(r"qrator|qrtr", re.I), "any"),
    ("Distil Networks",
     re.compile(r"distil|distil_captcha", re.I), "any"),

    # --- Asia-Pacific WAFs ---
    ("Tencent Cloud WAF",
     re.compile(r"tencent|waf-tencent|qcloud", re.I), "any"),
    ("Alibaba Cloud WAF",
     re.compile(r"aliyun|alibaba|alicdn|x-swc", re.I), "any"),
    ("Baidu Cloud WAF",
     re.compile(r"baidu|yunjiasu", re.I), "any"),
    ("360 Web Firewall",
     re.compile(r"360wzb|360webmaster|qihoo", re.I), "any"),
    ("Anquanbao",
     re.compile(r"anquanbao|jsluid|jsl_clearance", re.I), "any"),
    ("Yundun",
     re.compile(r"yundun|ydns", re.I), "any"),
    ("NSFocus",
     re.compile(r"nsfocus|NSFOCUS", re.I), "any"),
    ("Topsec",
     re.compile(r"topsec|TOPSEC", re.I), "any"),
    ("Antiy",
     re.compile(r"antiy|ANTiy", re.I), "any"),
    ("Safe3",
     re.compile(r"safe3|Safe3WAF", re.I), "any"),
    ("Velocidex",
     re.compile(r"velocidex", re.I), "any"),
    ("WebARX",
     re.compile(r"webarx|WebARX", re.I), "any"),
    ("Edgee",
     re.compile(r"edgee|edgee\.io", re.I), "any"),

    # --- ASP.NET / IIS / Azure ---
    ("ASP.NET Request Validation",
     re.compile(r"ASP\.NET|potentially dangerous Request|"
                r"HttpRequestValidationException", re.I), "any"),
    ("Microsoft Azure Front Door",
     re.compile(r"x-azure-ref|azurefd|azurefrontdoor", re.I), "any"),
    ("Microsoft IIS",
     re.compile(r"Microsoft-IIS|x-aspnet-version|x-powered-by.*ASP\.NET",
                re.I), "any"),

    # --- PHP / Laravel / Symfony filters ---
    ("Laravel CSRF",
     re.compile(r"laravel_session|x-csrf-token|laravel", re.I), "any"),
    ("Symfony CSRF",
     re.compile(r"symfony|csrf_token", re.I), "any"),

    # --- Misc / generic ---
    ("StackPath",
     re.compile(r"stackpath|x-sp-url", re.I), "any"),
    ("Section.io",
     re.compile(r"section\.io|x-section", re.I), "any"),
    ("Reblaze",
     re.compile(r"reblaze|rbzid", re.I), "any"),
    ("Teros",
     re.compile(r"teros|st8id", re.I), "any"),
    ("URLScan",
     re.compile(r"urlscan|URLScan", re.I), "any"),
    ("PowerfulBoomerang",
     re.compile(r"boomerang|powerfulboomerang", re.I), "any"),
]

# Status codes typically used by WAFs to indicate blocked requests.
_BLOCK_STATUS = {400, 401, 403, 404, 406, 419, 429, 444, 451, 493, 500, 502,
                 503, 999, 1000}

# Body hints that indicate a WAF block page (English + i18n).
_BLOCK_BODY_HINTS = re.compile(
    r"(request blocked|access denied|forbidden|firewall|security policy|"
    r"malicious|blocked by|not acceptable|waf|"
    r"web application firewall|request rejected|"
    r"suspicious activity|attack detected|"
    r"security rule|rule id|reference id|"
    r"request id|correlation id|incident id|"
    r"access has been blocked|protected by|"
    # Cloudflare-specific
    r"attention required|cf-ray|cloudflare|"
    # ModSecurity-specific
    r"mod_security|this error was generated|"
    # Akamai-specific
    r"akamai|access.denied|"
    # AWS WAF-specific
    r"request blocked by aws|"
    # Imperva-specific
    r"incapsula incident|"
    # Multilingual hints
    r"访问被拒绝|防火墙|安全策略|攻击|恶意请求|"
    r"アクセスが拒否されました|ファイアウォール|"
    r"접근이 거부되었습니다|방화벽|"
    r"Accès refusé|pare-feu|"
    r"Zugriff verweigert|Firewall|"
    r"Acceso denegado|cortafuegos|"
    r"Acesso negado|firewall)",
    re.IGNORECASE,
)

# Status codes that are strong block signals (vs. soft block like 404).
_STRONG_BLOCK_STATUS = {403, 406, 419, 444, 493, 999}


def detect(response) -> dict:
    """Return {'waf': name|None, 'blocked': bool, 'reason': str, 'confidence': str}.

    confidence is one of:
      "high"    -- vendor-specific cookie/header matched
      "medium"  -- body signature matched + block status
      "low"     -- generic block status / generic body hint
    """
    headers_blob = " ".join(f"{k}: {v}" for k, v in response.headers.items())
    cookies_blob = " ".join(v for k, v in response.headers.items()
                            if k.lower() == "set-cookie")
    body_excerpt = (response.text or "")[:8000]

    waf = None
    confidence = "none"
    signal_kind = "any"

    # Pass 1: cookie-based (highest specificity)
    for name, rx, kind in _WAF_SIGNATURES:
        if kind == "cookie" and rx.search(cookies_blob):
            waf = name
            confidence = "high"
            signal_kind = kind
            break
    # Pass 2: header-based
    if not waf:
        for name, rx, kind in _WAF_SIGNATURES:
            if kind in ("header", "any") and rx.search(headers_blob):
                waf = name
                confidence = "high"
                signal_kind = kind
                break
    # Pass 3: body-based
    if not waf:
        for name, rx, kind in _WAF_SIGNATURES:
            if kind in ("body", "any") and rx.search(body_excerpt):
                waf = name
                confidence = "medium"
                signal_kind = kind
                break

    blocked = False
    reason = ""
    if response.status_code in _STRONG_BLOCK_STATUS:
        blocked = True
        reason = f"HTTP {response.status_code}"
    elif response.status_code in _BLOCK_STATUS and waf:
        blocked = True
        reason = f"HTTP {response.status_code} + {waf} signature"
    elif waf and _BLOCK_BODY_HINTS.search(body_excerpt):
        # Phase 122 fix: block-page HINTS are a BODY signal.  This used to
        # search full_blob (headers + body), so the vendor FINGERPRINT
        # headers themselves (Server: cloudflare / CF-RAY) matched the
        # cloudflare/cf-ray hint patterns -- every UNBLOCKED 200 response
        # from any fingerprinted WAF was classified as blocked, and
        # _try_payload then discarded every payload the WAF actually let
        # through (a silent false-negative generator on all WAF'd sites).
        # A real block page carries its hints in the BODY.
        blocked = True
        reason = f"{waf} block page signature"
    elif _BLOCK_BODY_HINTS.search(body_excerpt):
        # Block page hint without a vendor match.
        blocked = True
        reason = "generic block-page body signature"
        if not waf:
            waf = "Generic/Unknown WAF"
            confidence = "low"

    # If a strong block status is present without a vendor match, report
    # generic so the operator knows evasion was triggered.
    if blocked and not waf and response.status_code in _STRONG_BLOCK_STATUS:
        waf = "Generic/Unknown WAF"
        confidence = "low"

    return {
        "waf": waf,
        "blocked": blocked,
        "reason": reason,
        "confidence": confidence,
        "signal": signal_kind if waf else "none",
    }


def detect_from_raw(status_code: int, headers: dict, body: str) -> dict:
    """Detect WAF from raw response components (no Response object needed).

    Useful for async scanners that don't have a requests.Response.
    """
    class _R:
        pass
    r = _R()
    r.status_code = status_code
    r.headers = headers
    r.text = body
    return detect(r)


def list_known_wafs() -> list[str]:
    """Return the list of WAF vendor names known to the detector."""
    seen = []
    for name, _, _ in _WAF_SIGNATURES:
        if name not in seen:
            seen.append(name)
    return seen


def is_waf_signature(text: str) -> str | None:
    """Quick check: does the given text contain any WAF signature?

    Returns the WAF name if matched, else None.
    """
    if not text:
        return None
    for name, rx, _ in _WAF_SIGNATURES:
        if rx.search(text):
            return name
    return None
